# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/buaa/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/buaa/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/buaa/CLionProjects/rlnc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/buaa/CLionProjects/rlnc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/buaa/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/buaa/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buaa/CLionProjects/rlnc/CMakeFiles /home/buaa/CLionProjects/rlnc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buaa/CLionProjects/rlnc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rlnc

# Build rule for target.
rlnc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rlnc
.PHONY : rlnc

# fast build rule for target.
rlnc/fast:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/build
.PHONY : rlnc/fast

codec.o: codec.cpp.o

.PHONY : codec.o

# target to build an object file
codec.cpp.o:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/codec.cpp.o
.PHONY : codec.cpp.o

codec.i: codec.cpp.i

.PHONY : codec.i

# target to preprocess a source file
codec.cpp.i:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/codec.cpp.i
.PHONY : codec.cpp.i

codec.s: codec.cpp.s

.PHONY : codec.s

# target to generate assembly for a file
codec.cpp.s:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/codec.cpp.s
.PHONY : codec.cpp.s

gf.o: gf.cpp.o

.PHONY : gf.o

# target to build an object file
gf.cpp.o:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/gf.cpp.o
.PHONY : gf.cpp.o

gf.i: gf.cpp.i

.PHONY : gf.i

# target to preprocess a source file
gf.cpp.i:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/gf.cpp.i
.PHONY : gf.cpp.i

gf.s: gf.cpp.s

.PHONY : gf.s

# target to generate assembly for a file
gf.cpp.s:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/gf.cpp.s
.PHONY : gf.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/main.cpp.s
.PHONY : main.cpp.s

test_codec.o: test_codec.cpp.o

.PHONY : test_codec.o

# target to build an object file
test_codec.cpp.o:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/test_codec.cpp.o
.PHONY : test_codec.cpp.o

test_codec.i: test_codec.cpp.i

.PHONY : test_codec.i

# target to preprocess a source file
test_codec.cpp.i:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/test_codec.cpp.i
.PHONY : test_codec.cpp.i

test_codec.s: test_codec.cpp.s

.PHONY : test_codec.s

# target to generate assembly for a file
test_codec.cpp.s:
	$(MAKE) -f CMakeFiles/rlnc.dir/build.make CMakeFiles/rlnc.dir/test_codec.cpp.s
.PHONY : test_codec.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rlnc"
	@echo "... codec.o"
	@echo "... codec.i"
	@echo "... codec.s"
	@echo "... gf.o"
	@echo "... gf.i"
	@echo "... gf.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_codec.o"
	@echo "... test_codec.i"
	@echo "... test_codec.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

